[build]
  command = "npm install --legacy-peer-deps && CI= npx react-scripts build"
  publish = "build"

[[redirects]]
  from = "/supabase/*"
  to = "https://yfetdazutkxvaixbhnok.supabase.co/:splat"
  status = 200
  force = true
  headers = {X-Special-Header = "yes"}
